### PR TITLE
Update and extend German translation

### PR DESCRIPTION
**Pull request by wlhlm**
Improve the German translation. ~~Also, change "Dukt" to "Leitung".~~

I wasn't too sure about what Viaducts are going to do.

### CODE REVIEW

**Comment by skyboy** [comment]
Viaducts are for transporting people

**Comment by Vexatos** [comment]
Just call them "Viadukt", it's latinized enough for it to work.

**Comment by wlhlm** [comment]
When I hear "Viadukt", I think of this:



which is miles away from the technology Thermal Dynamics provides. You think it's appropriate?

I definitely agree that the current translation "Überleitung" needs improvements.

**Comment by Vexatos** [comment]
@wlhlm The name "duct" is a direct reference to aquaeducts. "Duct" really is just a Latin term. It is very much appropriate.

**Comment by wlhlm** [comment]
Ok, I've updated branch to update the viaduct translation and reverted the "Dukt" -> "Leitung"-change. The main reason was to differentiate them from similar systems.

Mainly in modded, there are ducts (TD), conduits (EIO), and pipes (BC, etc.) and I want to keep this distinction in the German localisation.

**Comment by Vexatos** [comment]
:+1:

**Pull request merged**
